import 'package:tim_ui_kit_sticker_plugin/utils/tim_custom_face_data.dart';

class TUIKitStickerConstData {
  static final List<CustomEmojiFaceData> emojiList = [
    CustomEmojiFaceData(name: '4399', icon: "6.png",isEmoji: true,
        list: ["微笑.png","色.png","发呆.png","酷拽.png","抠鼻.png","流泪.png","捂脸.png","发怒.png"
          ,"呲牙.png","尬笑.png","害羞.png","调皮.png","舔屏.png","看.png","爱心.png","比心.png","赞.png","鼓掌.png","感谢.png",
          "抱抱你.png","玫瑰.png","灵机一动.png","耶.png","打脸.png","大笑.png","机智.png","送心.png","666.png","闭嘴.png","来看我.png",
          "一起加油.png","哈欠.png","震惊.png","晕.png","衰.png","困.png","疑问.png","泣不成声.png","小鼓掌.png","大金牙.png","偷笑.png",
          "石化.png","思考.png","吐血.png","可怜.png","嘘.png","撇嘴.png","笑哭.png","奸笑.png","得意.png","憨笑.png","坏笑.png","抓狂.png",
          "泪奔.png","钱.png","恐惧.png","愉快.png","快哭了.png","翻白眼.png","互粉.png","我想静静.png","委屈.png","鄙视.png","飞吻.png",
          "再见.png","紫薇别走.png","听歌.png","求抱抱.png","绝望的凝视.png","不失礼貌的微笑.png","不看.png","裂开.png","干饭人.png","吐舌.png",
          "呆无辜.png","白眼.png","熊吉.png","猪头.png","冷漠.png","微笑袋鼠.png","凝视.png","暗中观察.png","二哈.png","菜狗.png","黑脸.png","展开说说.png",
          "蜜蜂狗.png","摸头.png","皱眉.png","擦汗.png","红脸.png","做鬼脸.png","强.png","如花.png","吐.png","惊喜.png","敲打.png","奋斗.png","吐彩虹.png",
          "大哭.png","嘿哈.png","加好友.png","惊恐.png","惊讶.png","囧.png","难过.png","斜眼.png","阴险.png","悠闲.png","咒骂.png","吃瓜群众.png",
          "绿帽子.png","真的会谢.png","达咩.png","敢怒不敢言.png","投降.png","求求了.png","眼含热泪.png","叹气.png","好开心.png","不是吧.png","动动脑子.png",
          "表面微笑.png","表面呲牙.png","鞠躬.png","躺平.png","九转大肠.png","敲木鱼.png","不你不想.png","一头乱麻.png","kisskiss.png","你不大行.png",
          "噢买尬.png","宕机.png","还得是我.png","6.png","脸疼.png","他急了.png","苦涩.png","逞强落泪.png","强壮.png","碰拳.png","OK.png","击掌.png",
          "左上.png","握手.png","抱拳.png","勾引.png","拳头.png","弱.png","胜利.png","右边.png","左边.png","亚运鼓掌.png","金牌.png","手花.png","嘴唇.png",
          "心碎.png","凋谢.png","啤酒.png","咖啡.png","蛋糕.png","礼物.png","撒花.png","加一.png","减一.png","okk.png","V5.png","绝.png",
          "给力.png","红包.png","屎.png","发.png","我太难了.png","18禁.png","炸弹.png","去污粉.png","西瓜.png","加鸡腿.png","我酸了.png","握爪.png",
          "太阳.png","月亮.png","给跪了.png","蕉绿.png","扎心.png","胡瓜.png","yyds.png","emo.png","开心兔.png","招财兔.png","年兽兔.png",
          "打call.png","栓Q.png","无语.png","雪人.png","雪花.png","圣诞树.png","平安果.png","圣诞帽.png","气球.png","干杯.png","烟花.png","福.png",
          "candy.png","糖葫芦.png","虎头.png","饺子.png","鞭炮.png","元宝.png","灯笼.png","锦鲤.png","巧克力.png","汤圆.png","情书.png","iloveyou.png",
          "戒指.png","小黄鸭.png","棒棒糖.png","纸飞机.png","必胜.png","粽子.png"]),
    CustomEmojiFaceData(
        name: '4349',
        icon: "naughty.png",
        isEmoji: true,
        list: [
          "loveYou.png",
          "love.png",
          "loveHeart.png",
          "arrogant.png",
          "superciliousLook.png",
          "lollipop.png",
          "embrace.png",
          "claspFist.png",
          "blastedRebar.png",
          "despise.png",
          "shutUp.png",
          "firecrackers.png",
          "shit.png",
          "wipeSweat.png",
          "ribbon.png",
          "coloredBall.png",
          "kitchenKnife.png",
          "bad.png",
          "bankNote.png",
          "carriage.png",
          "yawn.png",
          "soldier.png",
          "cry.png",
          "cake.png",
          "knife.png",
          "proud.png",
          "lightBulb.png",
          "fade.png",
          "naughty.png",
          "cloudy.png",
          "daze.png",
          "tremble.png",
          "aircraft.png",
          "blowKiss.png",
          "struggle.png",
          "windmill.png",
          "awkward.png",
          "seduce.png",
          "applause.png",
          "shy.png",
          "sillySmile.png",
          "lantern.png",
          "Xi.png",
          "snicker.png",
          "wave.png",
          "lookBack.png",
          "hunger.png",
          "excitement.png",
          "streetDance.png",
          "terrified.png",
          "surprised.png",
          "coffee.png",
          "kowtow.png",
          "lovely.png",
          "pitiful.png",
          "pickNose.png",
          "skeleton.png",
          "cool.png",
          "willCry.png",
          "sleepy.png",
          "candle.png",
          "basketball.png",
          "coldSweat.png",
          "giftBag.png",
          "gift.png",
          "sweat.png",
          "tear.png",
          "mahjong.png",
          "microphone.png",
          "cat.png",
          "kissYou.png",
          "rose.png",
          "rice.png",
          "noodle.png",
          "feedingBottle.png",
          "sad.png",
          "alarmClock.png",
          "anger.png",
          "sulk.png",
          "football.png",
          "beer.png",
          "ladybug.png",
          "curlLip.png",
          "tableTennis.png",
          "car.png",
          "great.png",
          "knock.png",
          "frog.png",
          "embarrassed.png",
          "fist.png",
          "weak.png",
          "flirting.png",
          "sofa.png",
          "delete.png",
          "lightning.png",
          "victory.png",
          "showLove.png",
          "pistol.png",
          "decline.png",
          "sleep.png",
          "sun.png",
          "ropeSkipping.png",
          "jump.png",
          "titter.png",
          "spit.png",
          "grievance.png",
          "handshake.png",
          "watermelon.png",
          "rain.png",
          "scare.png",
          "offerKiss.png",
          "banana.png",
          "chineseChess.png",
          "heartbreak.png",
          "envelope.png",
          "panda.png",
          "shh.png",
          "drug.png",
          "doubt.png",
          "insidious.png",
          "rightLocomotive.png",
          "rightHum.png",
          "rightTaiChi.png",
          "umbrella.png",
          "moon.png",
          "halo.png",
          "bye.png",
          "bomb.png",
          "torment.png",
          "tissue.png",
          "swearing.png",
          "pig.png",
          "crazy.png",
          "circle.png",
          "baredTeeth.png",
          "diamondRing.png",
          "leftLocomotive.png",
          "leftHum.png",
          "leftTaiChi.png",
          "NO.png",
          "OK.png",
        ]),
    CustomEmojiFaceData(
        name: 'tcc1',
        icon: "Smile.png",
        isEmoji: true,
        list: [
          "Like.png",
          "OK.png",
          "Smile.png",
          "Expect.png",
          "Blink.png",
          "Guffaw.png",
          "KindSmile.png",
          "Haha.png",
          "Cheerful.png",
          "Speechless.png",
          "Amazed.png",
          "Sorrow.png",
          "Complacent.png",
          "Silly.png",
          "Lustful.png",
          "Giggle.png",
          "Kiss.png",
          "Wail.png",
          "TearsLaugh.png",
          "Trapped.png",
          "Mask.png",
          "Fear.png",
          "BareTeeth.png",
          "FlareUp.png",
          "Yawn.png",
          "Tact.png",
          "Stareyes.png",
          "ShutUp.png",
          "Sigh.png",
          "Hehe.png",
          "Silent.png",
          "Surprised.png",
          "Askance.png",
          "Shit.png",
          "Monster.png",
          "Daemon.png",
          "Rage.png",
          "Fool.png",
          "Pig.png",
          "Cow.png",
          "AI.png",
          "Skull.png",
          "Bombs.png",
          "Coffee.png",
          "Cake.png",
          "Beer.png",
          "Flower.png",
          "Watermelon.png",
          "Rich.png",
          "Heart.png",
          "Moon.png",
          "Sun.png",
          "Star.png",
          "RedPacket.png",
          "Celebrate.png",
          "Bless.png",
          "Fortune.png",
          "Convinced.png",
          "Prohibit.png",
          "666.png",
          "857.png",
          "Knife.png",
        ])
  ];
  static final emojiMapList = {
    'loveYou': '爱你',
    'love': "爱情",
    'loveHeart': "爱心",
    'arrogant': '傲慢',
    'superciliousLook': '白眼',
    "lollipop": '棒棒糖',
    "embrace": '抱抱',
    "claspFist": '抱拳',
    "blastedRebar": '爆筋',
    "despise": '鄙视',
    "shutUp": '闭嘴',
    "firecrackers": '鞭炮',
    "shit": '便便',
    "wipeSweat": '擦汗',
    "ribbon": '彩带',
    "coloredBall": '彩球',
    "kitchenKnife": '菜刀',
    "bad": '差劲',
    "bankNote": "钞票",
    "carriage": '车厢',
    "yawn": '打哈欠',
    "soldier": '大兵',
    "cry": "大哭",
    "cake": '蛋糕',
    "knife": "刀",
    "proud": '得意',
    "lightBulb": '灯泡',
    "fade": '凋谢',
    "naughty": '调皮',
    "cloudy": '多云',
    "daze": '发呆',
    "remble": '发抖t',
    "aircraft": '飞机',
    "blowKiss": '飞吻',
    "struggle": '奋斗',
    "windmill": '风车',
    "awkward": '尴尬',
    "seduce": '勾引',
    "applause": '鼓掌',
    "shy": '害羞',
    "sillySmile": '憨笑',
    "lantern": '红灯笼',
    "Xi": '红双喜',
    "snicker": '坏笑',
    "wave": '挥手',
    "lookBack": '回头',
    "hunger": '饥饿',
    "excitement": '激动',
    "streetDance": '街舞',
    "terrified": '惊恐',
    "surprised": '惊讶',
    "coffee": '咖啡',
    "kowtow": '磕头',
    "lovely": '可爱',
    "pitiful": '可怜',
    "pickNose": '抠鼻',
    "skeleton": '骷髅',
    "cool": '酷',
    "willCry": '快哭了',
    "sleepy": '困',
    "candle": '蜡烛',
    "basketball": '篮球',
    "coldSweat": '冷汗',
    "giftBag": '礼品袋',
    "gift": '礼物',
    "sweat": '流汗',
    "tear": '流泪',
    "mahjong": '麻将',
    "microphone": '麦克风',
    "cat": '猫咪',
    "kissYou": '么么哒',
    "rose": '玫瑰',
    "rice": '米饭',
    "noodle": '面条',
    "feedingBottle": '奶瓶',
    "sad": '难过',
    "alarmClock": '闹钟',
    "anger": '怒',
    "sulk": '怄火',
    "football": '皮球',
    "beer": '啤酒',
    "ladybug": '瓢虫',
    "curlLip": '撇嘴',
    "tableTennis": '乒乓',
    "car": '汽车',
    "great": '强',
    "knock": '敲打',
    "frog": '青蛙',
    "embarrassed": '糗大了',
    "fist": '拳头',
    "weak": '弱',
    "flirting": '色',
    "sofa": '沙发',
    "delete": '删除',
    "lightning": '闪电',
    "victory": '胜利',
    "showLove": '示爱',
    "pistol": '手枪',
    "decline": '衰',
    "sleep": '睡觉',
    "sun": '太阳',
    "ropeSkipping": '跳绳',
    "jump": '跳跳',
    "titter": '偷笑',
    "spit": '吐',
    "grievance": '委屈',
    "handshake": "握手",
    "watermelon": '西瓜',
    "rain": '下雨',
    "scare": '吓',
    "offerKiss": '献吻',
    "banana": '香蕉',
    "chineseChess": '象棋',
    "heartbreak": '心碎了',
    "envelope": '信封',
    "panda": '熊猫',
    "shh": '嘘',
    "drug": '药',
    "doubt": '疑问',
    "insidious": '阴险',
    "rightLocomotive": '右车头',
    "rightHum": '右哼哼',
    "rightTaiChi": "右太极",
    "umbrella": '雨伞',
    "moon": '月亮',
    "halo": '晕',
    "bye": '再见',
    "bomb": '炸弹',
    "torment": '折磨',
    "tissue": '纸巾',
    "swearing": '咒骂',
    "pig": '猪头',
    "crazy": '抓狂',
    "circle": '转圈',
    "baredTeeth": '龇牙',
    "diamondRing": "钻戒",
    "leftLocomotive": '左车头',
    "leftHum": '左哼哼',
    "leftTaiChi": "左太极",
    "NO": "NO",
    "OK": 'OK',
  };
  static const List<int> defaultUnicodeEmojiList = [
    128513,
    128514,
    128515,
    128516,
    128517,
    128521,
    128522,
    128523,
    128524,
    128525,
    128527,
    128530,
    128531,
    128532,
    128534,
    128536,
    128538,
    128540,
    128542,
    128544,
    128545,
    128546,
    128547,
    128548,
    128549,
    128552,
    128553,
    128554,
    128555,
    128557,
    128560,
    128561,
    128562,
    128563,
    128565,
    128567,
    128568,
    128569,
    128570,
    128571,
    128572,
    128573,
    128574,
    128575,
    128576,
    128581,
    128582,
    128583,
    128584,
    128585,
    128586,
    128587,
    128588,
    128589,
    128590,
    128591,
    9989,
    9994,
    9995,
    10060,
    10062,
    10067,
    10068,
    10069,
    10071,
    10133,
    10134,
    10135,
    10160,
    128640,
    128643,
    128644,
    128645,
    128647,
    128649,
    128652,
    128655,
    128657,
    128658,
    128659,
    128661,
    128663,
    128665,
    128666,
    128674,
    128676,
    128677,
    128679,
    128680,
    128681,
    128682,
    128683,
    128684,
    128685,
    128690,
    128694,
    128697,
    128698,
    128699,
    128700,
    128701,
    128702,
    128704,
    127374,
    127377,
    127378,
    127379,
    127380,
    127381,
  ];
}
